### ISSUE TITLE
Create a paywall using lightning 

### ISSUE THREAD

**Issue by QA2A** [pingojo/website#8]
```[tasklist]
### Tasks
- [ ] Setup Lightning node
- [ ] Integrate paywall with lightning node to receive payments
- [ ] update user model to check subscription type
```

Setting up a Django website to take payments via a Lightning Network node involves multiple steps, including setting up the Lightning node, integrating it with Django, and ensuring secure payment processing. Below is a detailed explanation of the steps:

1. Setting Up the Lightning Node
To accept Lightning payments, you'll need a Lightning Network node. There are several implementations, but the most popular ones are:

LND (Lightning Network Daemon): The most commonly used implementation, developed by Lightning Labs.
c-lightning (Core Lightning): A lightweight and customizable implementation by Blockstream.
Eclair: Another implementation, which is more developer-friendly.
We'll focus on setting up LND here.

Step 1.1: Install LND
Install Golang (required for building LND):

bash
Copy code
sudo apt-get update
sudo apt-get install -y golang
Clone the LND repository:

bash
Copy code
git clone https://github.com/lightningnetwork/lnd.git
cd lnd
Install dependencies:

bash
Copy code
make && make install
Create a configuration file:
Create a directory for LND configuration if it doesn't exist:

bash
Copy code
mkdir ~/.lnd
Create a configuration file:

bash
Copy code
nano ~/.lnd/lnd.conf
Add the following configuration:

makefile
Copy code
[Application Options]
alias=YOUR_NODE_ALIAS
color=#68F442
restlisten=localhost:8080
tlsextraip=YOUR_SERVER_IP
maxpendingchannels=5

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=localhost:8332
bitcoind.rpcuser=YOUR_RPC_USERNAME
bitcoind.rpcpass=YOUR_RPC_PASSWORD
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
Replace YOUR_NODE_ALIAS, YOUR_SERVER_IP, YOUR_RPC_USERNAME, and YOUR_RPC_PASSWORD with your actual values.

Run LND:
Start LND:

bash
Copy code
lnd
Unlock your wallet:
You may need to create or unlock your wallet if running LND for the first time:

bash
Copy code
lncli create
To unlock:

bash
Copy code
lncli unlock
Fund your node:
Send some Bitcoin to the address generated by your LND node:

bash
Copy code
lncli newaddress p2wkh
Open a channel:
Once your transaction confirms, you can open a channel with another node:

bash
Copy code
lncli connect PUBKEY@NODE_IP
lncli openchannel PUBKEY 1000000
Step 1.2: Install and Configure Bitcoind
LND relies on a Bitcoin node to interact with the Bitcoin blockchain. If you don't have bitcoind installed:

Install Bitcoin Core:

bash
Copy code
sudo apt-get install bitcoind
Configure Bitcoin Core:
Create the Bitcoin configuration file:

bash
Copy code
nano ~/.bitcoin/bitcoin.conf
Add the following configuration:

makefile
Copy code
server=1
daemon=1
txindex=1
rpcuser=YOUR_RPC_USERNAME
rpcpassword=YOUR_RPC_PASSWORD
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
Replace YOUR_RPC_USERNAME and YOUR_RPC_PASSWORD with your chosen credentials.

Start Bitcoin Core:

bash
Copy code
bitcoind -daemon
2. Integrating Lightning with Django
Now that your LND node is running, you can start integrating it into a Django project.

Step 2.1: Setup a Django Project
Create a Django project:

bash
Copy code
django-admin startproject lightning_payment
cd lightning_payment
Create a Django app:

bash
Copy code
python manage.py startapp payments
Install necessary libraries:
You'll need grpcio, googleapis-common-protos, and python-bitcoinlib to interact with LND's gRPC API:

bash
Copy code
pip install grpcio googleapis-common-protos python-bitcoinlib
Step 2.2: Setup gRPC with LND
Generate LND gRPC stubs:
Download the LND gRPC proto files:

bash
Copy code
git clone https://github.com/lightningnetwork/lnd.git
Then generate Python files:

bash
Copy code
python -m grpc_tools.protoc --proto_path=./lnd/lnrpc --python_out=. --grpc_python_out=. lnd/lnrpc/rpc.proto
Move the generated files to your Django project.

Create a Lightning service in Django:
In your payments app, create a service to interact with LND.

python
Copy code
import os
import grpc
import lightning_pb2 as ln
import lightning_pb2_grpc as lnrpc

class LndService:
    def __init__(self):
        cert = open(os.path.expanduser('~/.lnd/tls.cert'), 'rb').read()
        creds = grpc.ssl_channel_credentials(cert)
        self.channel = grpc.secure_channel('localhost:10009', creds)
        self.stub = lnrpc.LightningStub(self.channel)

    def get_invoice(self, value):
        request = ln.Invoice(value=value)
        response = self.stub.AddInvoice(request)
        return response.payment_request

    def check_payment(self, r_hash):
        request = ln.PaymentHash(r_hash=r_hash)
        response = self.stub.LookupInvoice(request)
        return response.settled
Step 2.3: Integrate Payment Logic into Views
Create a View to Generate Invoices:

python
Copy code
from django.http import JsonResponse
from .services import LndService

def create_invoice(request):
    amount = request.GET.get('amount')
    lnd_service = LndService()
    payment_request = lnd_service.get_invoice(value=int(amount))
    return JsonResponse({'payment_request': payment_request})
Create a View to Check Payment Status:

python
Copy code
from django.http import JsonResponse
from .services import LndService

import grpc
from django.http import JsonResponse
from .models import LightningPayment
from lnrpc import rpc_pb2 as ln, rpc_pb2_grpc as lnrpc
from django.views import View
from django.conf import settings

class CreateInvoiceView(View):
    def post(self, request):
        amount = request.POST.get('amount')
        
        # Connect to LND node
        cert = open(settings.LND_TLS_CERT, 'rb').read()
        creds = grpc.ssl_channel_credentials(cert)
        channel = grpc.secure_channel(f'{settings.LND_NODE_IP}:{settings.LND_NODE_PORT}', creds)
        stub = lnrpc.LightningStub(channel)
        
        # Create a new invoice
        request = ln.Invoice(value=int(amount))
        response = stub.AddInvoice(request)
        
        # Save the invoice to the database
        LightningPayment.objects.create(
            invoice=response.payment_request,
            amount=amount,
        )
        
        return JsonResponse({
            'invoice': response.payment_request,
            'r_hash': response.r_hash.hex()
        })

class CheckPaymentStatusView(View):
    def get(self, request, r_hash):
        # Connect to LND node
        cert = open(settings.LND_TLS_CERT, 'rb').read()
        creds = grpc.ssl_channel_credentials(cert)
        channel = grpc.secure_channel(f'{settings.LND_NODE_IP}:{settings.LND_NODE_PORT}', creds)
        stub = lnrpc.LightningStub(channel)
        
        # Check invoice status
        request = ln.PaymentHash(r_hash=bytes.fromhex(r_hash))
        response = stub.LookupInvoice(request)
        
        # Update payment status in the database
        if response.settled:
            payment = LightningPayment.objects.get(invoice=response.payment_request)
            payment.paid = True
            payment.save()
        
        return JsonResponse({'paid': response.set

from django.db import models

class LightningPayment(models.Model):
    invoice = models.CharField(max_length=1024)
    paid = models.BooleanField(default=False)
    amount = models.DecimalField(max_digits=10, decimal_places=8)
    created_at = models.DateTimeField(auto_now_add=True)

#!/bin/bash

# Update and upgrade the system
sudo apt-get update -y
sudo apt-get upgrade -y

# Install required dependencies
sudo apt-get install -y build-essential autoconf libtool libgmp-dev libsqlite3-dev python3 python3-pip python3-dev \
                        virtualenv git libsodium-dev libzmq3-dev libqrencode-dev libcurl4-openssl-dev \
                        libffi-dev libssl-dev jq

# Set up Go environment
GO_VERSION="1.20.7"
wget https://golang.org/dl/go$GO_VERSION.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go$GO_VERSION.linux-amd64.tar.gz
echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile
source ~/.profile

# Verify Go installation
go version

# Download and install LND (Lightning Network Daemon)
git clone https://github.com/lightningnetwork/lnd.git
cd lnd
make install
cd ~

# Create a configuration directory for LND
mkdir ~/.lnd
cd ~/.lnd

# Set up LND configuration
cat <<EOF > ~/.lnd/lnd.conf
[Application Options]
alias=MyNode
color=#FFFF00
maxpendingchannels=5

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpcuser=YOUR_RPC_USER
bitcoind.rpcpass=YOUR_RPC_PASSWORD
bitcoind.rpchost=localhost
bitcoind.rpcport=8332
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[autopilot]
autopilot.active=1
autopilot.maxchannels=5
autopilot.allocation=0.6
EOF

# Replace placeholders with your actual RPC username and password
sed -i "s/YOUR_RPC_USER/$(grep rpcuser ~/.bitcoin/bitcoin.conf | cut -d'=' -f2)/" ~/.lnd/lnd.conf
sed -i "s/YOUR_RPC_PASSWORD/$(grep rpcpassword ~/.bitcoin/bitcoin.conf | cut -d'=' -f2)/" ~/.lnd/lnd.conf

# Create a systemd service for LND
sudo bash -c 'cat <<EOF > /etc/systemd/system/lnd.service
[Unit]
Description=LND Lightning Daemon
After=bitcoind.service

[Service]
ExecStart=/usr/local/bin/lnd --externalip=YOUR_VPS_IP
User=$(whoami)
Group=$(whoami)
LimitNOFILE=128000
Type=simple
TimeoutSec=120
Restart=always
RestartSec=60
StartLimitInterval=300
StartLimitBurst=5

[Install]
WantedBy=multi-user.target
EOF'

# Enable and start the LND service
sudo systemctl enable lnd
sudo systemctl start lnd

# Check LND status
sudo systemctl status lnd

echo "LND setup complete!"
